/** Modal that shows the AI-generated post-CAB report with a copy button. */
import { useState } from 'react';

export function CabReportModal({ text, onClose }) {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="between">
          <h2 style={{ margin: 0 }}>📄 Post-CAB report</h2>
          <button className="ghost small" onClick={onClose}>Close</button>
        </div>
        <div style={{ whiteSpace: 'pre-wrap', fontSize: '.9rem', marginTop: '.75rem' }}>{text}</div>
        <div className="between" style={{ marginTop: '1rem' }}>
          <button onClick={copy}>{copied ? 'Copied ✔' : 'Copy to clipboard'}</button>
          <small>Generated by Claude — review before sending.</small>
        </div>
      </div>
    </div>
  );
}
